[licenses]
allow = [
  "BSD-3-Clause",
  "BSD-2-Clause",
  "ISC",
  "MIT",
  "Apache-2.0",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
  "Zlib",
  "OpenSSL",
  "Apache-2.0 WITH LLVM-exception",
  "MPL-2.0",
]
private = { ignore = true }

[advisories]
ignore = ["RUSTSEC-2024-0436", "RUSTSEC-2023-0071"]

[bans]
deny = [
  "openssl-sys", # no openssl.
]
multiple-versions = "allow"

[sources]
# allow-git = ["eldritch-link-rust", "nunu-types-rs"]
allow-git = [
  "git+ssh://git@github.com/nunu-ai/eldritch-link-rust.git?branch=main",
  "git+ssh://git@github.com/nunu-ai/nunu-types.git?branch=main",
  "git+ssh://git@github.com/nunu-ai/winput.git?branch=main",
]
